package com.garageplug.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.garageplug.model.Customer;
import com.garageplug.model.CustomerDTO;
import com.garageplug.model.LoginDTO;
import com.garageplug.service.CustomerService;

import jakarta.validation.Valid;

@RestController
@RequestMapping("/garageplug")
public class CustomerController {
	
	@Autowired
	CustomerService customerService;

	@PostMapping("/user/signup") //controller for creating an account of a customer
	public ResponseEntity<Customer> createAccount(@Valid @RequestBody CustomerDTO customer) throws Exception{
		
		// CustomerDTO is taken in request body to avoid unnecessary parameters that are autogenerated for Customer class
		
		Customer cust = customerService.createAccount(customer);
		
		return new ResponseEntity<Customer>(cust, HttpStatus.CREATED);
	}
	
	@PostMapping("/user/login") // login purpose
	public ResponseEntity<String> userLogin(@Valid @RequestBody LoginDTO user) throws Exception{
		
		String msg = customerService.loginUser(user);
		
		return new ResponseEntity<String>(msg, HttpStatus.OK);
	}
}
